import {StyleSheet} from "react-native";


const Styles= StyleSheet.create({

    sign1MainView:{
        flex:1,
        backgroundColor:"#FBFBFB"
       },
       firstLogoView:{
       alignItems:"center",
       marginTop:45
       },
       logoView:{
        height:68,
        width:215,
        //position:"absolute",
        marginTop:45
          
    },
       headingView:{
        alignItems:"center",
        marginTop:45
       },
       textOneStyle:{
        fontSize:25,
        fontWeight:"bold"
       },
       textTwoStyle:{
        fontSize:18,
        color:"#757D85",
        marginTop:10
       },
       secondView:{
        marginTop:20,
        marginLeft:15
       },
       inputOneView:{
       },
       textThreeStyle:{
        fontSize:17,
        color:"#525C67",
       },
       inputView:{
        marginTop:10,
        backgroundColor:"#DDDDDD",
        borderTopEndRadius:10,
        borderTopStartRadius:10,
        borderEndEndRadius:10,
        borderEndStartRadius:10,
        width:400,
        height:50,
        flexDirection:"row"
       },
       textInput:{
        fontSize:18,
        marginTop:1,
        width:330,
        marginLeft:15
       },
       iconImage:{
        height:25,
        width:25,
        marginLeft:20,
        marginTop:10
       },
       inputTwoView:{
        marginTop:10
       },
       bottomView:{
        marginTop:10
       },
       forgetView:{
        alignItems:"flex-end",
        marginRight:15
       },
       forgetTextStyle:{
        fontSize:17,
        color:"#525C67",
       },
       signView:{
        marginTop:10,
        backgroundColor:"#FDDED4",
        borderTopEndRadius:10,
        borderTopStartRadius:10,
        borderEndEndRadius:10,
        borderEndStartRadius:10,
        width:400,
        height:50,
        alignItems:"center",
       },
       signText:{
        marginTop:15,
        fontSize:18,
        color:"#FBFBFB"
       },
       textFourMainView:{
        alignItems:"center"
       },
       textFourView:{
        flexDirection:"row",
        marginTop:15,
       },
       textFour:{
        fontSize:17,
        color:"#757D85",
       },
       signUpView:{
        marginLeft:5,
       },
       signUp:{
        fontSize:17,
        color:"#FF6C44"
       },
       socialIconView:{
        top:180
       },
       faceBookView:{
        flexDirection:"row",
        backgroundColor:"#0064C0",
        borderTopEndRadius:10,
        borderTopStartRadius:10,
        borderEndEndRadius:10,
        borderEndStartRadius:10,
        width:400,
        height:50,
        alignItems:"center"
       },
       socialImage:{
        height:25,
        width:25,
        left:80
       },
       socialFbText:{
        fontSize:18,
        color:"#FFFFFF",
        left:90
       },
       googleView:{
        flexDirection:"row",
        backgroundColor:"#DDDDDD",
        borderTopEndRadius:10,
        borderTopStartRadius:10,
        borderEndEndRadius:10,
        borderEndStartRadius:10,
        width:400,
        height:50,
        alignItems:"center"
       },
       socialGoogleText:{
        fontSize:18,
        color:"#000000",
        left:90
       },
    
});

export default Styles
