import {StyleSheet} from "react-native";

const Styles= StyleSheet.create({

    mainView:{
        flex:1,
      },
      firstView:{
        flex:1.6,
        backgroundColor:"#FFFFFF",
      },
      firstUpperView:{
        alignItems:"center"
      },
      backgroundImage:{
       height:500,
       width:435
      },
      logoOnView:{
        height:68,
        width:215,
        position:"absolute",
        top:60     
      },
      logoFavFoodView:{
        height:300,
        width:215,
        position:"absolute", 
        top:230   
      },
      secondOnOneView:{
        flex:1,
        backgroundColor:"white",
      },
      firstHeadingView:{
        alignItems:"center",
        top:30
      },
      chooseText:{
        fontSize:28,
        fontWeight:"bold"
      },
      text:{
        marginTop:10,
        fontSize:17,
        color:"#757D85",
        textAlign:"center"
      },
      slideBarView:{
        marginTop:40,
        flexDirection:"row",
        marginRight:20,
      },
      squareView:{
        height:10,
        width:30,
        backgroundColor:"#FF6C44",
        borderRadius:10
      },
      circleOneView:{
       marginLeft:10,
        height:10,
        width:10,
        backgroundColor:"#FF6C44",
        borderCurve:"circular",
       borderRadius:10
      },
      bottomButtonView:{
        marginTop:60,
        flexDirection:"row",
      },
      skipView:{
        marginLeft:70,
        marginTop:10
      },
      skipText:{
        fontSize:22,
        color:"#525C67"
      },
      nextView:{
        height:50,
        width:180,
        backgroundColor:"#FF6C44",
        alignItems:"center",
        borderRadius:10,
        marginLeft:70
      },
      nextText:{
        fontSize:23,
        color:"#FFFFFF",
        top:10
      },
});

export default Styles ;   
