import {StyleSheet} from "react-native";

const Styles= StyleSheet.create({

    mainView:{
        flex:1,
      },
      firstView:{
        flex:1.6,
        backgroundColor:"#FFFFFF",
      },
      firstUpperView:{
        alignItems:"center"
      },
      backgroundImage:{
       height:500,
       width:435
      },
      logoOnView:{
        height:68,
        width:215,
        position:"absolute",
        top:60     
      },
      logoBackground_2View:{
        height:300,
        width:280,
        position:"absolute", 
        top:220  
       },
      secondOnOneView:{
        flex:1,
        backgroundColor:"white",
      },
      firstHeadingView:{
        alignItems:"center",
        top:30
      },
      chooseText:{
        fontSize:28,
        fontWeight:"bold"
      },
      text:{
        marginTop:10,
        fontSize:17,
        color:"#757D85",
        textAlign:"center"
      },
      slideBarView:{
        marginTop:40,
        flexDirection:"row",
        marginRight:20,
      },
      squareView:{
        height:10,
        width:30,
        backgroundColor:"#FF6C44",
        borderRadius:10,
        marginLeft:10
      },
      circleView:{
       marginLeft:10,
        height:10,
        width:10,
        backgroundColor:"#FF6C44",
       borderRadius:10
      },
      bottomButtonView:{
        marginTop:30,
      },
      letsView:{
        height:50,
        width:350,
        backgroundColor:"#FF6C44",
        borderRadius:10,
      },
      letsText:{
        fontSize:18,
        color:"#FFFFFF",
        top:10,
        fontWeight:"bold",
        textAlign:"center"
      }
});

export default Styles ;   
